meta:
  plugin: FatPressor
  updated: 2026-01-22T11:15:00Z

current:
  stage: verify
  task_id: null
  task_title: null

  resume:
    context: "ISSUE-002 resolved. Windows glow fixed by removing filters and using brighter colors."
    next_action: "Continue with LAUNCH or additional fixes"

stages:
  concept: done
  struct: done
  surface: done
  craft: done
  verify: done
  launch: pending

tasks:
  done:
    - id: fatpressor_concept
      title: "[CONCEPT] Define plugin vision"
    - id: fatpressor_struct
      title: "[STRUCT] Design DSP architecture"
    - id: fatpressor_surface
      title: "[SURFACE] Design UI mockup"
    - id: fatpressor_task_001
      title: "[CRAFT] Setup CMake project and plugin scaffold"
    - id: fatpressor_task_002
      title: "[CRAFT] Implement APVTS parameters"
    - id: fatpressor_task_003
      title: "[CRAFT] Implement SidechainDetector"
    - id: fatpressor_task_004
      title: "[CRAFT] Implement EnvelopeFollower"
    - id: fatpressor_task_005
      title: "[CRAFT] Implement GainComputer"
    - id: fatpressor_task_006
      title: "[CRAFT] Implement TubeSaturation"
    - id: fatpressor_task_007
      title: "[CRAFT] Implement TransformerColoration"
    - id: fatpressor_task_008
      title: "[CRAFT] Implement CompressorCore"
    - id: fatpressor_task_009
      title: "[CRAFT] Implement WebView UI"
    - id: fatpressor_task_010
      title: "[CRAFT] Implement interactive compression graph"
    - id: fatpressor_task_011
      title: "[CRAFT] Implement metering"
    - id: fatpressor_task_012
      title: "[CRAFT] Integration and testing"
  active: null
  queue: []

# ENHANCE workflow tracking
enhancements:
  completed:
    - id: "ENHANCE-001"
      title: "Add preset system with factory presets and user preset saving"
      version: "0.1.0 → 0.2.0"
      date: "2026-01-22"
      tasks:
        - id: fatpressor_enhance_001_task_001
          title: "[ENHANCE] Implement PresetManager C++ class"
        - id: fatpressor_enhance_001_task_002
          title: "[ENHANCE] Create 20 factory presets"
        - id: fatpressor_enhance_001_task_003
          title: "[ENHANCE] Implement preset browser UI + C++ bridge"
        - id: fatpressor_enhance_001_task_004
          title: "[ENHANCE] Wire preset system and integrate with WebView"
        - id: fatpressor_enhance_001_task_005
          title: "[ENHANCE] Test and version bump to 0.2.0"
  active: null
  active_tasks:
    done: []
    active: null
    queue: []

# FIX workflow tracking
issues:
  resolved:
    - id: "ISSUE-002"
      title: "SVG glow renders as squares on Windows WebView2"
      version: "0.2.0 → 0.2.1"
      date: "2026-01-22"
      tasks:
        - id: fatpressor_issue_002_fix
          title: "[ISSUE] Fix: Windows SVG glow rendering"
        - id: fatpressor_issue_002_test
          title: "[ISSUE] Test: Verify glow on Windows"
  active: null
  active_tasks:
    done: []
    active: null
    queue: []

validation:
  pluginval_vst3: passed
  pluginval_au: passed
  strictness_level: 5

artifacts:
  spec_hash: "a1b2c3d4"
  parameters:
    - threshold
    - ratio
    - attack
    - release
    - output
    - mix
    - fat
  formats:
    - vst3
    - au
    - standalone
  locations:
    vst3: "~/Library/Audio/Plug-Ins/VST3/FatPressor.vst3"
    au: "~/Library/Audio/Plug-Ins/Components/FatPressor.component"
